config/routes.rb
Bank::Application.routes.draw do
  resource :welcome, :only => :index
  root :to => 'welcome#index'
  resources :users ,:only => :show do
    resources :transactions,:only => [:new,:create]
  end

  resource :sessions ,:only => [:create,:destroy]

end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_protected :balance
  belongs_to :user

  has_many :credit_transactions, :foreign_key => :to_account, :class_name => "Transaction",:order => :created_at
  has_many :debit_transactions, :foreign_key => :from_account, :class_name => "Transaction",:order => :created_at

end

app/models/transaction.rb
class TransactionValidator< ActiveModel::Validator
  def validate(record)
    if record.new_record?
      if record.source_account
         if record.source_account.balance - record.amount < 0
           record.errors[:base] << "Sorry! you dont have sufficient funds for this transaction"
         end
         if record.to_account
           if Account.where(:id => record.to_account).empty?
             record.errors[:base] << "Sorry! You have entered a wrong account number"
           end
         end
        if record.to_account.eql?(record.from_account)
          record.errors[:base] << "You cannot transfer money to yourself"
        end
      else
        record.errors[:base] << "Sorry! something went wrong, Please contact our support team"
      end
    end
  end
end

class Transaction < ActiveRecord::Base
  belongs_to :source_account,:foreign_key => :from_account,:class_name => "Account"
  belongs_to :destination_account,:foreign_key => :to_account,:class_name => "Account"

  has_one :source_user,:through => :source_account,:source => :user
  has_one :destination_user,:through => :destination_account,:source => :user
  validates_with TransactionValidator
  after_create :modify_balance_for_users
  validates_numericality_of :to_account,:from_account,:amount
  validates_presence_of :to_account,:from_account,:amount
  private
  def modify_balance_for_users

    self.transaction do
      self.source_account.balance=self.source_account.balance - self.amount
      self.source_account.save
      self.destination_account.balance = self.destination_account.balance + self.amount
      self.destination_account.save
      self.is_completed=true
      self.save
    end
  end
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  attr_accessible :email, :gender, :name, :date_of_birth,:password
  attr_accessor :password

  has_one :account

  has_many :debit_transactions,:through => :account,:source => :debit_transactions
  has_many :credit_transactions,:through => :account,:source => :credit_transactions

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i , :message => "Please enter a valid email"
  validates_presence_of :email,:name,:password
  validates_uniqueness_of :email, :message => "This email address is already registered"

  before_save :hash_new_password, :if=>:password_changed?
  after_create :set_account_for_user

  def balance
    self.account.balance
  end
  def transactions
    transactions=debit_transactions + credit_transactions
    transactions.sort_by! {|t| t.created_at}
    return transactions
  end
  def self.authenticate(email, password)
    if user = find_by_email(email)
      if BCrypt::Password.new(user.encrypted_password).is_password? password
        return user
      end
    end
    return nil
  end

  private

  def password_changed?
    !@password.blank?
  end

  def hash_new_password
    self.encrypted_password = BCrypt::Password.create(@password)
  end

  def set_account_for_user
    account=Account.new
    account.user=self
    account.balance=100
    account.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate_user
    unless session[:users].present? && session[:users].eql?(@user)
      flash[:notice]="Please Login first"
      reset_session
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #before_filter :authenticate_user

  def create
    user = User.authenticate(params[:email],params[:password])
    if user
      session[:users] = user
      redirect_to user_path(:id => user.id)
    else
      flash[:error] = 'Invalid email/password combination' # Not quite right!
      redirect_to root_path
    end
  end

  def destroy
    s
    redirect_to root_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :load_user,:authenticate_user
  def new
    @transaction=Transaction.new
    @transaction.from_account=@user.account.id

  end
  def create
    @transaction=Transaction.new
    @transaction.from_account=params[:transaction][:from_account]
    @transaction.to_account=params[:transaction][:to_account]
    @transaction.amount=params[:transaction][:amount]
    if @transaction.save
      flash[:notice]= "Transaction completed successfully"
      redirect_to user_path(:id => @user.id)
    else
      render :new
    end
  end
  private
  def load_user
    @user=User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :load_user,:authenticate_user
  def show

  end
  private
  def load_user
    @user=User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'application'
  def index
     render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bank</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%if session[:users].present?%>
<%=link_to "Log Out", sessions_path,:method => :delete%>
<%end%>


<% flash.each do |type, message|%>
    <div>
     <%= message%>
    </div>
<%end%>
<%= yield %>

</body>
</html>

app/views/transactions/new.html.haml
- if @transaction.errors.any?
  =@transaction.errors.full_messages
=form_for [@user,@transaction] do |f|
  =f.hidden_field :from_account
  =f.label :to_account,"To Account"
  =f.text_field :to_account
  =f.label :amount,"Amount"
  =f.text_field :amount
  =f.submit :Execute

app/views/users/show.html.haml
%h2
  = "Welcome #{@user.name}"
= "Account Number #{@user.account.id}"
="Your current balance #{@user.account.balance}"
%div
  =link_to "New Transaction",new_user_transaction_path(:user_id => @user.id)
  %h3
    History
  %table
    %tr
      %th
        Name
      %th
        Account
      %th
        At
      %th
        Amount
      %th
        Completed
    %tbody
      -@user.transactions.each do |transaction|
        - is_debit_transaction= transaction.source_user.eql?(@user)
        %tr
          -if is_debit_transaction
            %td= transaction.destination_user.name
            %td= transaction.destination_user.account.id
            %td= transaction.created_at
            %td= "-#{transaction.amount}"
            %td= transaction.is_completed? ? "Confirmed":"Error"
          -else
            %td= transaction.source_user.name
            %td= transaction.source_user.account.id
            %td= transaction.created_at
            %td= "+#{transaction.amount}"
            %td= transaction.is_completed? ? "Confirmed":"Error"

app/views/welcome/index.html.haml
.home
  %h1 Welcome to the Bank Application
.sign-form
  =form_tag sessions_path do
    = text_field_tag :email
    = password_field_tag :password
    =submit_tag "Login"